import { useState } from 'react';
import { compileFortiOS, migrateWithProfile, parseFortiOS, validateMigration, type MigrationFinding } from './utils/fortiEngine';
import { fortigate100ETo120G714Profile } from './migrations/profiles';

function severityClass(severity: MigrationFinding['severity']) {
  return severity === 'critical' ? 'text-red-400' : severity === 'high' ? 'text-orange-400' : severity === 'medium' ? 'text-yellow-400' : 'text-slate-300';
}

export default function App() {
  const [originalText, setOriginalText] = useState('');
  const [migratedText, setMigratedText] = useState('');
  const [findings, setFindings] = useState<MigrationFinding[]>([]);
  const [stats, setStats] = useState<{ configs: number; edits: number; commands: number; transformedCommands: number } | null>(null);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  const [reportUrl, setReportUrl] = useState<string | null>(null);

  const buildReport = (items: MigrationFinding[], statistics: typeof stats) => {
    const counts = items.reduce<Record<string, number>>((acc, item) => { acc[item.status] = (acc[item.status] ?? 0) + 1; return acc; }, {});
    return [
      '# FortiAlign Migration Report',
      '',
      `Source: ${fortigate100ETo120G714Profile.sourceModel} / ${fortigate100ETo120G714Profile.sourceFirmware}`,
      `Target: ${fortigate100ETo120G714Profile.destinationModel} / ${fortigate100ETo120G714Profile.destinationFirmware}`,
      '',
      '## Result',
      `- BLOCK: ${counts.BLOCK ?? 0}`,
      `- MANUAL: ${counts.MANUAL ?? 0}`,
      `- REVIEW: ${counts.REVIEW ?? 0}`,
      `- TRANSFORMED: ${counts.TRANSFORMED ?? 0}`,
      `- PASS: ${counts.PASS ?? 0}`,
      '',
      '## Statistics',
      `- Config blocks: ${statistics?.configs ?? 0}`,
      `- Edit blocks: ${statistics?.edits ?? 0}`,
      `- Commands: ${statistics?.commands ?? 0}`,
      `- Transformed commands: ${statistics?.transformedCommands ?? 0}`,
      '',
      '## Findings',
      ...items.map(item => `### ${item.id} — ${item.severity.toUpperCase()} — ${item.status}\n- **${item.title}**\n- ${item.message}\n- Path: ${item.sourcePath ?? 'n/a'}\n- Recommendation: ${item.recommendation}`),
      '',
      '> Generated by FortiAlign. This report is an engineering aid; target-device validation is required before production deployment.',
    ].join('\n');
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const rawText = await file.text();
    setOriginalText(rawText);

    const ast = parseFortiOS(rawText);
    const result = migrateWithProfile(ast, fortigate100ETo120G714Profile);
    const validation = validateMigration(result, fortigate100ETo120G714Profile);
    const outputText = compileFortiOS(result.ast);

    setMigratedText(outputText);
    setFindings(validation);
    setStats(result.statistics);

    if (downloadUrl) URL.revokeObjectURL(downloadUrl);
    if (reportUrl) URL.revokeObjectURL(reportUrl);
    setDownloadUrl(URL.createObjectURL(new Blob([outputText], { type: 'text/plain' })));
    setReportUrl(URL.createObjectURL(new Blob([buildReport(validation, result.statistics)], { type: 'text/markdown' })));
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 p-6 flex flex-col gap-6">
      <header className="flex flex-col lg:flex-row justify-between items-center bg-slate-900 p-4 rounded-lg border border-slate-800 gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-100">FortiAlign — FortiGate Migration & Assurance</h1>
          <p className="text-sm text-slate-400">100E / FortiOS 7.0.19 → 120G / FortiOS 7.4.12</p>
        </div>
        <div className="flex gap-3 items-center flex-wrap justify-center">
          <label className="cursor-pointer px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded font-medium text-sm">
            Import .conf
            <input type="file" accept=".conf,.txt" className="hidden" onChange={handleFileUpload} />
          </label>
          {downloadUrl && <a href={downloadUrl} download="fortialign-migrated.conf" className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded font-medium text-sm">Download Config</a>}
          {reportUrl && <a href={reportUrl} download="fortialign-migration-report.md" className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded font-medium text-sm">Download Report</a>}
        </div>
      </header>

      {stats && (
        <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          {[
            ['Config blocks', stats.configs], ['Edit blocks', stats.edits], ['Commands', stats.commands], ['Transformed', stats.transformedCommands]
          ].map(([label, value]) => <div key={label} className="bg-slate-900 border border-slate-800 rounded-lg p-4"><div className="text-xs text-slate-500 uppercase">{label}</div><div className="text-2xl font-bold">{value}</div></div>)}
        </section>
      )}

      {findings.length > 0 && (
        <section className="bg-slate-900 border border-slate-800 rounded-lg p-4">
          <div className="flex justify-between items-center mb-3"><h2 className="text-sm font-semibold uppercase tracking-wider">Migration findings</h2><span className="text-xs text-slate-500">{findings.length} findings</span></div>
          <div className="max-h-80 overflow-auto space-y-2">
            {findings.map(item => <div key={item.id} className="border border-slate-800 rounded p-3 text-sm"><div className="flex gap-3"><span className="font-mono text-slate-500">{item.id}</span><span className={severityClass(item.severity)}>{item.severity.toUpperCase()}</span><span className="text-slate-400">{item.status}</span><strong>{item.title}</strong></div><p className="text-slate-400 mt-1">{item.message}</p><p className="text-slate-500 mt-1">{item.recommendation}</p></div>)}
          </div>
        </section>
      )}

      <main className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-6 min-h-[600px]">
        <div className="flex flex-col gap-2"><h2 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Source Configuration</h2><div className="flex-1 bg-slate-900 border border-slate-800 rounded-lg p-4 overflow-auto max-h-[70vh]">{originalText ? <pre className="text-xs font-mono text-slate-300 whitespace-pre-wrap">{originalText}</pre> : <div className="h-full flex items-center justify-center text-slate-500 italic text-sm">Import a FortiGate configuration to begin.</div>}</div></div>
        <div className="flex flex-col gap-2"><h2 className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">Migration Candidate</h2><div className="flex-1 bg-slate-900 border border-emerald-900/30 rounded-lg p-4 overflow-auto max-h-[70vh]">{migratedText ? <pre className="text-xs font-mono text-emerald-400 whitespace-pre-wrap">{migratedText}</pre> : <div className="h-full flex items-center justify-center text-slate-500 italic text-sm">Awaiting configuration import.</div>}</div></div>
      </main>
    </div>
  );
}
